=== alhidalgb/Trabajo_Sistemas_Distribuidos/ClasesXML/jugador_apuesta.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT listapuestas (jugador*)>

<!ATTLIST listapuestas
  fecha CDATA #REQUIRED
>

<!ELEMENT jugador (apuesta+)>

<!ATTLIST jugador
  id ID #REQUIRED
>

<!ELEMENT apuesta (tipo, valor, cantidad)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT valor (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>

=== alhidalgb/Trabajo_Sistemas_Distribuidos/ClasesXML/jugador_apuesta.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE listapuestas SYSTEM "jugador_apuesta.dtd">

<!-- Este documento sirve como almacen de todas las apuestas relizadas -->

<listapuestas fecha="2025-11-22">
    <jugador id="pepe">
        <apuesta>
            <tipo>NUMERO</tipo>
            <valor>7</valor>
            <cantidad>10.0</cantidad>
        </apuesta>
    </jugador>
    
    <jugador id="ana">
        <apuesta>
            <tipo>COLOR</tipo>
            <valor>ROJO</valor>
            <cantidad>50.5</cantidad>
        </apuesta>
    </jugador>
</listapuestas>
